name: HTML Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kód
        uses: actions/checkout@v3

      - name: Validace HTML
        uses: Cyb3r-Jak3/html-validator-action@v2
        with:
          files: index.html
