name: CI - Testy a Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Získat repozitář
      - name: Checkout kód
        uses: actions/checkout@v3

      # 2) Nastavit Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3) Instalovat závislosti
      - name: Instalace závislostí
        run: npm install

      # 4) Spustit testy (Jest)
      - name: Spuštění testů
        run: npm test
